name: draw_your_image
description: A Flutter package which enables users to draw with fingers.
version: 0.0.6
homepage: https://github.com/chooyan-eng/draw_your_image

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: